import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ClerkProvider } from '@clerk/nextjs';
import UserMenu from "@/components/UserMenu";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.variable} antialiased`}
        >
          <nav className="p-4 bg-gray-100 flex justify-between items-center">
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="text-blue-500 hover:underline">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/button-demo" className="text-blue-500 hover:underline">
                  ボタンデモ
                </Link>
              </li>
              <li>
                <Link href="/users" className="text-blue-500 hover:underline">
                  ユーザー一覧
                </Link>
              </li>
            </ul>
            <UserMenu />
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
