-- CreateTable
CREATE TABLE "MENU_TBL" (
    "menuNo" TEXT NOT NULL,
    "menuName" TEXT NOT NULL,
    "provideDate" TIMESTAMP(3) NOT NULL,
    "isReserved" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MENU_TBL_pkey" PRIMARY KEY ("menuNo")
);

-- CreateTable
CREATE TABLE "BUSENESS_CARENDER_TBL" (
    "date" TIMESTAMP(3) NOT NULL,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "isHoliday" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BUSENESS_CARENDER_TBL_pkey" PRIMARY KEY ("date")
);

-- CreateTable
CREATE TABLE "RESERVATION_TBL" (
    "id" TEXT NOT NULL,
    "menuNo" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "reservationTime" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RESERVATION_TBL_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "MENU_TBL_provideDate_idx" ON "MENU_TBL"("provideDate");

-- CreateIndex
CREATE INDEX "RESERVATION_TBL_userId_idx" ON "RESERVATION_TBL"("userId");

-- CreateIndex
CREATE INDEX "RESERVATION_TBL_menuNo_idx" ON "RESERVATION_TBL"("menuNo");

-- AddForeignKey
ALTER TABLE "RESERVATION_TBL" ADD CONSTRAINT "RESERVATION_TBL_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER_TBL"("userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RESERVATION_TBL" ADD CONSTRAINT "RESERVATION_TBL_menuNo_fkey" FOREIGN KEY ("menuNo") REFERENCES "MENU_TBL"("menuNo") ON DELETE CASCADE ON UPDATE CASCADE;
